/* Auto-generated by gen-colors.sh — do not edit manually */
static const char wal_bg[]      = "#0D172B";  /* color0 - background         */
static const char wal_fg[]      = "#aab0c3";  /* color7 - foreground         */
static const char wal_border[]  = "#767b88";  /* color8 - inactive border    */
static const char wal_bg_sel[]  = "#DC694C";  /* color4 - selected bg/border */
static const char wal_fg_sel[]  = "#0D172B";  /* color0 - selected fg        */
