#!/usr/bin/env bash
# ─────────────────────────────────────────────
#  gen-colors.sh
#  Reads pywal16 color cache and writes colors.h
#  for dwm to #include in config.h.
#  Called automatically by wal.sh after wal runs.
# ─────────────────────────────────────────────

DWM_DIR="${HOME}/dwm"   # ← change this to your dwm source dir if different
WAL_COLORS="${HOME}/.cache/wal/colors.sh"

if [[ ! -f "$WAL_COLORS" ]]; then
    echo "gen-colors: pywal cache not found at $WAL_COLORS" >&2
    exit 1
fi

source "$WAL_COLORS"

# color0  = darkest background
# color7  = normal foreground (light)
# color8  = bright black (dim, good for inactive borders)
# color4  = blue accent (selected bg / active border)
# color0  = background used as fg on selected items (contrast)

cat > "${DWM_DIR}/colors.h" << CEOF
/* Auto-generated by gen-colors.sh — do not edit manually */
static const char wal_bg[]      = "${color0}";  /* color0 - background         */
static const char wal_fg[]      = "${color7}";  /* color7 - foreground         */
static const char wal_border[]  = "${color8}";  /* color8 - inactive border    */
static const char wal_bg_sel[]  = "${color4}";  /* color4 - selected bg/border */
static const char wal_fg_sel[]  = "${color0}";  /* color0 - selected fg        */
CEOF

echo "gen-colors: wrote ${DWM_DIR}/colors.h"
echo "  bg      = ${color0}"
echo "  fg      = ${color7}"
echo "  border  = ${color8}"
echo "  sel_bg  = ${color4}"
echo "  sel_fg  = ${color0}"
