#!/usr/bin/env bash
. ~/.cache/wal/colors.sh 2>/dev/null || { FG="#cdd6f4"; BG="#1e1e2e"; }
FG="${color7}"; BG="${color0}"
mem=$(free -h | awk '/^Mem/ {print $3"/"$2}' | sed 's/i//g')
echo "^c${FG}^^b${BG}^  ${mem} ^d^"
