/* Auto-generated by gen-colors.sh — do not edit manually */
static const char wal_bg[]      = "#0E0D0E";  /* color0 - background         */
static const char wal_fg[]      = "#f4f5f5";  /* color7 - foreground         */
static const char wal_border[]  = "#aaabab";  /* color8 - inactive border    */
static const char wal_bg_sel[]  = "#CBCDD1";  /* color4 - selected bg/border */
static const char wal_fg_sel[]  = "#0E0D0E";  /* color0 - selected fg        */
